name: real_image

image_shape: [3, 480, 480]
dataset_path: /home/ubuntu/IL_my/policy_data/20250311_185257
obs_keys: &obs_keys ['camera_1', 'camera_2', 'agent_pose']

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_1:
      shape: ${task.image_shape}
      type: rgb
    camera_2:
      shape: ${task.image_shape}
      type: rgb
    agent_pose:
      shape: [8]
      type: low_dim
  action: 
    shape: [8]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robot_image_dataset.RobotImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

